# Automatically create release
#
on:
  push:
    tags:
      - '*'  # (auto-create on new tag)
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build executable
        run: python 

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: dist/your_script  # Adjust the path to your generated executable
