# Creates release with build artifact

- name: Publish to GitHub Releases
  uses: actions/create-release@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    tag_name: ${{ github.ref }}
    release_name: Release ${{ github.ref }}
    body: |
      Release ${{ github.ref }} contains the latest executable.
      See the relevant executable for Linux, Windows and MacOS.
      If any bugs occur, please send them to https://github.com/Wolfmyths/Genshin-Stopwatch/issues
  - name: Upload artifact
    uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      asset_path: dist/your_script  # Adjust the path to your generated executable
      asset_name: genshin_stopwatch.exe  # Adjust the desired name for the executable
      asset_content_type: application/octet-stream

